version: '3'
services:
  # Nginx server configuration
  web:
    image: nginx:1.17
    container_name: 'mvc-webserver'
    depends_on:
      - "docker-mysql-mvc"
      - php
    links:
      - "docker-mysql-mvc"
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "8889:80"

  # Php-fpm configuration
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
#    image: php:7.4-fpm
    container_name: 'mvc-php'
    volumes:
      - ./:/var/www/html
      - ./php:/usr/local/etc/php/php.ini

  # Mysql configuration
  docker-mysql-mvc:
    image: mysql:5.7
    container_name: docker-mysql-mvc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: j4w>t9T+`h#/+W/a
      MYSQL_DATABASE: mvc
      MYSQL_USER: mvc
      MYSQL_PASSWORD: J"@MM4s2fZc~FB+r
    ports:
      - "3309:3306"
    volumes:
      - /docker/dbdata_mvc:/var/lib/mysql

  phpmyadmin:
    container_name: docker-mysql-mvc-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  dbdata_mvc: